---
referrals:
- :title: Moving a bed for COACH so that she can reach things behind it
  :subtitle: The dust gets to their chest so this small task would be of great help
    to her.
  :description: COACH hasn't been able to clean behind their bed for a long time, as
    she is unable to move it. The bed needs moving out so COACH can clean behind it
    and reach a couple of belongings, then moving back.
- :title: Dig some borders so that COACH can be happier with their garden
  :subtitle: COACH would be really relieved to have their borders tidied up
  :description: COACH asked if some runners would be able to spend a couple of hours
    doing some digging so that she can lay down some prepared borders by their flowerbeds.
- :title: To dismantle a bed and remove furniture for COACH
  :subtitle: To give space for hospital bed so COACH can come home from hospital
  :description: 'This may need two missions but the whole task is: Help the family
    with dismantling the bed (they will provide tools).  Take out as much furniture
    as possible from the room, (and potentially for a second mission on another day)
    lay floor protector, and stick down with gaffer tape. Lean the bed parts against
    a wall. '
- :title: General garden tidy for COACH
  :subtitle: It will help him manage their garden
  :description: General garden help for COACH. He doesn't have any tools but says it'll
    largely need runners to pull out weeds rather than use tools so you may want to
    bring some gloves!
- :title: COACH needs help in their garden
  :subtitle: He is unable to do it and their wife is ill so it would really help them
    enjoy their garden again
  :description: General garden maintenance, a bit of weeding and mowing the lawn.
- :title: 'Garden clean up: weeding and trimming back.'
  :subtitle: COACH to do this herself but is no longer able and it bothers her.
    Her husband is 90 and in poor health.
  :description: Garden needs a general tidy up weeding and cutting back. They have
    all the tools available.
- :title: Clearing the garden for COACH so he can put it to use
  :subtitle: 'COACH would like to participate in very light gardening, take pride in
    their garden and know that it is being put to productive use by others '
  :description: "COACH has a garden which is overgrown, and he is hoping can be put
    to use a bit more in the future. Garden needs clearing, cutting back, weeding
    etc. \r\n\r\nGetting this to the point that he can look after it may be a nice
    project, so he's open to having a few runners get cracking on it!"
- :title: COACH needs a garden tidy up
  :subtitle: She will be able to enjoy their garden again.
  :description: COACH needs a hand in the garden. Weeds pulling up, bushes to be trimmed
    and general tidy up. She has tools available and would be very grateful.
- :title: General garden tidy for COACH
  :subtitle: 'It would help their restore their garden to its former glory '
  :description: COACH used to take pride in their garden and she'd like to get it back
    on track. She has tools available.
- :title: Help in the garden for COACH
  :subtitle: She struggles to do this herself and would really like some more help
  :description: 'COACH has had some GoodGym help already but there''s more to do and
    she thinks it could really do with some GoodGym TLC and is very appreciative of
    our runners'' efforts. '
- :title: Cutting back shrubs for COACH
  :subtitle: COACH isn't able to take care of their garden herself
  :description: COACH would be very grateful for some help with cutting back shrubs
    in their garden. She is 85 years old and cannot take care of their garden herself.
    She has all the tools needed.
- :title: General garden tidy for COACH
  :subtitle: It will help their manage their garden after a stroke
  :description: General gardening help for COACH; weeding, trimming and tidying. She
    does have some tools available and wanted to buy more but we advised their against
    this so may involve using what she does have creatively. You also may want  to
    bring your own gloves!
- :title: 'Help COACH in their garden '
  :subtitle: So that  she can get their garden in order
  :description: 'COACH would like a couple of GoodGym runners to clear their flower bed,
    mow their lawn and wipe down a couple of outdoor kitchen windows that he cannot
    reach. '
- :title: General garden tidy up for COACH
  :subtitle: COACH will feel much better in their ground floor flat
  :description: COACH would like runners to pull up some weeds and tidy the garden
    up. She doesn't have  any tools but thinks that runners will be able to pull up
    the weeds with their hands so you may want to bring gloves!
- :title: General garden tidy for COACH
  :subtitle: COACH will be able to enjoy looking out on a neat and tidy garden.
  :description: A small front garden lawn needed mowing at the time of the referral
    but COACH has since managed to do this. He still has a few things round the garden
    that he'd like a hand with. COACH has the tools required.
- :title: COACH needs a hand on their allotment
  :subtitle: It will help COACH to safely be able to work on their allotment
  :description: COACH needs a hand moving some manure around on their allotment. Their
    allotments have had help from the York group before but she thinks this will be
    a bit of a smaller job. She has the tools available.
- :title: COACH's curtains are hanging down and need to be hooked back up to track .
  :subtitle: COACH says that the living room gets very cold in the winter if she is
    unable to drawer the curtains properly.
  :description: COACH would love some volunteers to try and help their out with their curtains.
    She's not sure if volunteers will definitely be able to do it but she'd love for
    them to have a go. May need to hook the curtains back in place.
- :title: Digging up and moving paving stones, weeding for COACH
  :subtitle: 'COACH will be able to enjoy their garden again '
  :description: "Weeding and general garden tidy up. COACH mentioned that she has about
    12 damaged paving stones that may need to be dug out and carried to the front
    of the property to be collected but only do this if you think it can be done safely.
    COACH has all the tools required, and bags for waste.\r\n"
- :title: Support with clearing the garden; weeding; trimming back plants.
  :subtitle: The client expressed he could arrange for friends to sit with him in
    garden.
  :description: Cleaning; trimming; wedding the garden. He does have rabbits and guinea
    pigs in the garden so perhaps not suitable for someone who is allergic.
- :title: Tidy up the small garden for COACH
  :subtitle: Client will enjoy the garden more
  :description: 'Client explained that there is not much to do, just a bit of tidying
    up and plant some new plants. She has all the tools but being 90 she does not
    have the energy to do the job herself. '
