:encouragement:
  - You can do it $NAME.
  - You can make a big difference $NAME.
  - We’re all behind you $NAME.
  - What’s stopping you $NAME?
  - Make it happen $NAME.
  - Dig deep $NAME.
  - Go $NAME!
  - Let’s do this $NAME.
  - Now’s the time $NAME.
  - Make the world a little bit better $NAME.
  - Act now $NAME.
  - We believe in you $NAME.
  - Create a story, $NAME.
  - Continue the adventure $NAME.
  - Be bold $NAME.
  - It’s going to happen $NAME.
  - You’re in charge $NAME.
  - The show must go on $NAME.
  - You’re the boss $NAME.
  - Where you go, others follow $NAME.
  - Set an example $NAME.
  - Continue your triumph $NAME.
  - Live up to the hype $NAME.
  - Continue the glory $NAME.
  - Set a record $NAME.
  - You have the power $NAME.
  - Perform a modern day miracle $NAME.
  - Show the world $NAME.
  - Now’s your chance $NAME.
  - Do something small that could make a big difference $NAME.
  - Keep the journey going $NAME.
  - Make the next part of the adventure $NAME.
  - Show someone you care $NAME.
  - You are a hero $NAME.
  - You know you can do it $NAME.
:exclamation:
  - "A short poem:"
  - A triumph, a spectacular triumph and a half.
  - All you need is love
  - An update for you.
  - And the crowd went wild...
  - Are you in the game?
  - Are you ready for this?
  - Are you sitting down?
  - As if by magic
  - At last
  - Aye carumba
  - Bake that cake.
  - Balling
  - BANG!
  - Bang on.
  - Bang.
  - Bazinga!
  - Believe it.
  - Believe.
  - Big Business
  - Big deal?
  - Big love
  - Big up.
  - Bloody hell.
  - Bonkers
  - Boom
  - Born to run.
  - Bosh.
  - Bravo!
  - Can you sign this for me
  - Casual.
  - Celebrate.
  - Champion
  - Change it up
  - Choose Life
  - "Clear your mind, think about this:"
  - Climb every mountain.
  - Connect.
  - Could you do this?
  - Could you go this fast?
  - Crikey.
  - Crivens!
  - Dang, that's good!
  - Did this just happen?
  - Ding Dong.
  - Divine.
  - Dominant.
  - Dominate.
  - Don't read this.
  - Dreamy.
  - Drop everything
  - Drop it like it's hot
  - Epic.
  - Everyone loves this.
  - Fantastico!
  - Far out!
  - Feel it.
  - Get in.
  - Get off the internet.
  - Get out there.
  - Give it all.
  - Glorious.
  - Go go go!
  - "Hard facts:"
  - Have you heard?
  - Healthy.
  - Heavens.
  - "Here we go:"
  - Here we go!
  - "Here's the detail:"
  - Hero.
  - Heroic
  - Hold the front page.
  - Holy smokes batman
  - Hoover the floor!
  - Houston we no longer have a problem
  - How do you keep fit?
  - How does this make you feel?
  - How long can you run?
  - Hug this screen
  - "Important event:"
  - In awe?
  - In the real world
  - In you we trust
  - Inspired.
  - Is this a dream
  - Is this a haiku?
  - Is this for real?
  - Is this true?
  - It's all in the eyes
  - It's happened.
  - Jammy dodgers.
  - Jeepers.
  - Jiminy Jillickers!
  - Jump up and down.
  - Keep on coming on
  - Ladies and Gentleman, your attention please.
  - Literally wow.
  - Live.
  - "Look at this:"
  - Look away.
  - Make some noise!
  - Mama-Miaaaaa!
  - Mary Poppins!
  - Massive.
  - Millions saw that.
  - Mission complete.
  - Mo Farah wishes he was you.
  - News just in.
  - Nice one!
  - No need for yoga.
  - No way!
  - No you just didn't - yes you just did!
  - Nuff Said
  - Oh yeah.
  - OK.
  - On it like a car bonnet.
  - On the attack.
  - On the move.
  - On the up.
  - Onwards.
  - Out of the ashes.
  - Picturesque.
  - Precious.
  - Pump up the volume.
  - Push forward.
  - Put on your finery.
  - Put your hands together.
  - Put your phone away.
  - Quiche Lorraine!
  - "Read this now:"
  - Relentless.
  - Remember this forever.
  - Respect.
  - Right on time.
  - Say NOTHING
  - Show some love.
  - Show your support.
  - Shut the front door.
  - "Shut your eyes:"
  - Siiiiiick.
  - Sing it loud.
  - "Some important info:"
  - "Some news for you:"
  - Spread the word.
  - Star dust sprinkling bad ass
  - STOP!! hammer time.
  - Strut baby strut
  - Take this in.
  - Tell your friends.
  - That moment when
  - That's right,
  - The nation loves you
  - The real deal.
  - This is a big moment.
  - "This is for you:"
  - This is it.
  - This is LIFE
  - This is live
  - This is real.
  - This is the moment.
  - This is the one.
  - This is the one.
  - This is the truth.
  - This is what life is about.
  - This needs shouting about.
  - This will change things.
  - Time to celebrate.
  - Time to relax.
  - Time to wind down.
  - Too cool for school
  - Too right...
  - Total belief.
  - Total confidence
  - Triumphant.
  - Turn up the stereo.
  - Unbelievable.
  - Wax on, Wax off.
  - We are all watching
  - What do you reckon?
  - What do you want to achieve?
  - What does this mean?
  - What would you feel like?
  - What's the point of life?
  - Where have you been?
  - Where's the camera crew
  - Who knew?
  - Woah!
  - Woohoo.
  - Wow.
  - Wowsers.
  - Yes Bruv.
  - Yes mate.
  - Yes please.
  - Yes!
  - You are better than ever before.
  - You are the best at what you do.
  - You can do this too.
  - You Hero You
  - You Phoenix you.
  - You rock
  - You've done it.
  - You've got the support of us all.
