---
:base:
  "5":
    "08:00": true
    "09:00": true
    "10:00": true
    "11:00": true
    "12:00": true
    "13:00": true
    "14:00": true
    "15:00": true
    "16:00": true
    "17:00": true
    "18:00": true
    "19:00": true
:home:
  "0":
    "08:00": true
    "19:00": true
  "1":
    "08:00": true
    "19:00": true
  "2":
    "08:00": true
    "19:00": true
  "3":
    "08:00": true
    "19:00": true
  "4":
    "08:00": true
    "19:00": true
  "5":
    "08:00": true
    "09:00": true
    "10:00": true
    "11:00": true
    "12:00": true
    "13:00": true
    "14:00": true
    "15:00": true
    "16:00": true
    "17:00": true
    "18:00": true
    "19:00": true
  "6":
    "08:00": true
    "09:00": true
    "10:00": true
    "11:00": true
    "12:00": true
    "13:00": true
    "14:00": true
    "15:00": true
    "16:00": true
    "17:00": true
    "18:00": true
    "19:00": true
